#!/usr/bin/env bash
# Remove editor/AI attribution lines from a commit message file.
# Sourced by prepare-commit-msg and commit-msg hooks.
strip_ai_attribution() {
  local msg_file="${1:?message file}"
  local tmp
  tmp="$(mktemp)"
  grep -Eiv \
    '^[[:space:]]*Co-authored-by:.*cursoragent@cursor\.com' \
    "$msg_file" > "$tmp" || true
  mv "$tmp" "$msg_file"

  tmp="$(mktemp)"
  grep -Eiv \
    '^[[:space:]]*Co-authored-by:[[:space:]]*(Cursor|GitHub[[:space:]]+Copilot|ChatGPT|Claude|OpenAI|Anthropic|Copilot|Cursor[[:space:]]+Agent)' \
    "$msg_file" > "$tmp" || true
  mv "$tmp" "$msg_file"

  tmp="$(mktemp)"
  grep -Eiv \
    '^(Made-with|Made with|Generated by)[[:space:]]+(Cursor|ChatGPT|Claude|Copilot)|^Signed-off-by:[[:space:]]*Cursor' \
    "$msg_file" > "$tmp" || true
  mv "$tmp" "$msg_file"
}

commit_msg_has_ai_attribution() {
  local msg_file="${1:?message file}"
  grep -Eiq \
    '^[[:space:]]*Co-authored-by:.*cursoragent@cursor\.com' \
    "$msg_file" && return 0
  grep -Eiq \
    '^[[:space:]]*Co-authored-by:[[:space:]]*(Cursor|GitHub[[:space:]]+Copilot|ChatGPT|Claude|OpenAI|Anthropic|Copilot|Cursor[[:space:]]+Agent)' \
    "$msg_file" && return 0
  grep -Eiq \
    '^(Made-with|Made with|Generated by)[[:space:]]+(Cursor|ChatGPT|Claude|Copilot)|^Signed-off-by:[[:space:]]*Cursor' \
    "$msg_file" && return 0
  return 1
}

commit_has_ai_attribution() {
  local sha="${1:?commit sha}"
  local author_email committer_email body
  author_email="$(git log -1 --format='%ae' "$sha" 2>/dev/null || true)"
  committer_email="$(git log -1 --format='%ce' "$sha" 2>/dev/null || true)"
  if [[ "$author_email" == *cursoragent@cursor.com* ]] \
    || [[ "$committer_email" == *cursoragent@cursor.com* ]]; then
    return 0
  fi
  body="$(git log -1 --format='%B' "$sha" 2>/dev/null || true)"
  if printf '%s\n' "$body" | grep -Eiq \
    'Co-authored-by:.*cursoragent@cursor\.com|Co-authored-by:[[:space:]]*Cursor'; then
    return 0
  fi
  return 1
}
