#!/usr/bin/env bash
# Scan the working tree for common AI/editor fingerprints (exit 1 if found).
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

fail=0

if [[ -d .cursor ]]; then
  echo "FAIL: .cursor/ present (editor agent config; should not be committed)" >&2
  fail=1
fi

list_files() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git ls-files
  else
    find . -type f \( -name '*.md' -o -name '*.sh' -o -name '*.rs' \) \
      ! -path './target/*' ! -path './.git/*' | sed 's|^\./||'
  fi
}

patterns=(
  'Co-authored-by:[[:space:]]*Cursor'
  'cursoragent@cursor\.com'
  'Generated by[[:space:]]+(Cursor|ChatGPT|Claude|Copilot)'
  'Made with[[:space:]]+Cursor'
  'as an AI'
  'For agentic workers'
  'IMPORTANT for the assistant'
)

while IFS= read -r f; do
  [[ -f "$f" ]] || continue
  case "$f" in
    scripts/check-no-ai-traces.sh|scripts/git-hooks/*) continue ;;
  esac
  for p in "${patterns[@]}"; do
    if grep -Eiq "$p" "$f" 2>/dev/null; then
      echo "FAIL: $f matches /$p/" >&2
      fail=1
    fi
  done
done < <(list_files)

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if git log --all --format='%B' | grep -Eiq 'Co-authored-by:[[:space:]]*Cursor|cursoragent@cursor\.com'; then
    echo "WARN: git history still contains Cursor Co-authored-by trailers (rewrite only if you intend to force-push)" >&2
  fi
fi

if [[ "$fail" -ne 0 ]]; then
  exit 1
fi
echo "OK: no AI/editor fingerprints in scanned files"
